language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/hal-blink


install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - qio platform install file://.

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
