build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/cmsis-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/libopencm3-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-hal-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-ll-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-blink"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: qio platform install file://.

test_script:
  - cmd: qio run -s -d %PLATFORMIO_PROJECT_DIR%
